apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgADwHy+okDkao4US7TuYbww/ng+460PBBsyIEEVL6TttE8BdV1lwGYlMWUV5LIwLCwqj3Ypvqjq2fk1Y+lUd9SaiS/4xbBbOrpM1Q7GTwC5Tsnn7g58pZKHJtm+JjqjkAxScG5+YFAmabz2DrugZv/ruFLuz3zhZQoEXIPykxkDIEk8utJSKKv4evPWWDKfr631L9TF9huBXr756chLniSdu+TX4a2ydmrb1KM8bz0z5wacK/qNtD0+tZ3ePzLKyGPQvyV2gfwbvjVYBiA/BVp52mvZur+SXdUIjXaVySZntVrK4mSbbmYhdi8yphiypCYGvqJwhMB1R/kPd9U5vIzRDsCgTGOYESBR2L/uDeRUIFMH76Mp+xDAC0FLwv3aKbK4xCW0hFE99DL0s72WSb0A+Uu9PLffAdX0RAXbnsrIQlneOUVzphQWYUVEI2NCPdnh1YIHd1T46jiLAJaja0HwDwvS5fhQey6lO/m7MtRG5lYsVmFmLR5tY6xhabi4LMg6C9YfKiWM+WmTWj3YTRlFQJKnsbmlhDEBzU5Fs4ntSpYLNBxul3UGYlY6MSgXKV81sBJKv5ElucFJX9LOPrLi78qVeU+fCaOseYXYnB/GjrfJWvjchhOBbZbLaAC1VikfrKXJO7V8Ss9VZbnvFkaPhPV66f7hcDGfyA6Y0CnSYJ6nwP7cvujfz926FNOV1YFATfhrFQ==
    user: AgAY0G1FhBcCxL53c2O6dpCEhEJgnq39dyoghcb0P+Z9LJpBMN1h5nVBSX9g+KTniISNqdYRVhtVaUvmu3QZyDRmYBssLAPhrvMRcjGzjIngGO6M62kONJ80Yf5zq8sTQ9T6kI7XgcLEoloTv76hJIteQGXIxtLUEspGpQH1a6mo2p8j7q39YzO6O9TNa8oOx838LePDUBStCaMzgZ77OJCvJmidg6OmKDDAqpUMBD8plobz5f40k9IPtw6cCdB3LK5IYRpK38Braey/rhLI61TkLUG8khRDh91YkVNgsgU+tPvnatyvA7ipkhobq8i6MMQTA/GYb+2mUVs+AcmUU/jxOMUIH4/mH5pY6TuSUEq345mWah+B5NJHQp6+6zYiexGEwk5JhY7TxztYyXNjetC+wAzScjpU5N0INwFfNLoMmrAfZ6gisNuPHd3OdTeAoFtWLZp8R4q/fvPQc4DTGZoiF1RKBGBA/3qfRF+FynqTZZqISj3ouE9+aHYaV9EX/Pa8aDefiT63QpQH5fIO+uRx9nIjzlD8rXUb+snZKH1NLyiE7AjzMLgRr4Hy7zBiXuIcxuLVE+1V0daQB4dwOBt3EnTsQUToIB5P53+y5+Aqm9XDAsGQFKsN25z7z1IbMzRo/ryWaCiTmgaM8TZtcFLfKphD2moUpElaJKwL7xBoazLg3VAYIq2Vmd/2ci3SUmAIrg6HQg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod
status: {}

