apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-tester
  namespace: prod
  annotations:
    fluxcd.io/ignore: "true"
spec:
  releaseName: helm-tester
  targetNamespace: prod
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.12.1
  values:
    fullnameOverride: helm-tester
    serviceAccountName: helm-tester
