apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: load-tester
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: loadtester
  timeout: 300
  chart:
    repository: https://flagger.app
    name: loadtester
    version:
  values:
    fullnameOverride: load-tester
