---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: load-tester
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: load-tester
  targetNamespace: prod
  timeout: 100
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.12.1
  value:
    fullnameOverride: load-tester
